import { test } from 'node:test'; import assert from 'node:assert/strict'; import { webcrypto } from 'node:crypto';
if (!(globalThis as typeof globalThis & {crypto?:Crypto}).crypto) Object.defineProperty(globalThis,'crypto',{value:webcrypto});
import { authenticate, mutationHeaders, redact } from '../src/http.ts'; import { Vault } from '../src/vault.ts'; import { AccountStore } from '../src/account.ts'; import { OpError } from '../src/types.ts';
const token='x'.repeat(32); const hex=async(s:string)=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(x=>x.toString(16).padStart(2,'0')).join('');
class Mem {m=new Map<string,unknown>();async get<T>(k:string){return this.m.get(k) as T|undefined}async put(x:Record<string,unknown>){for(const[k,v]of Object.entries(x))this.m.set(k,v)}}
async function expect(p:Promise<unknown>,status:number,code:string){await assert.rejects(p,(e:unknown)=>e instanceof OpError&&e.status===status&&e.code===code)}
test('auth matrix and mutation headers',async()=>{const raw=JSON.stringify([{id:'reader',sha256:await hex(token),scopes:['read'],accounts:['alpha']},{id:'admin',sha256:await hex('y'.repeat(32)),scopes:['admin'],accounts:['*']}]);await expect(authenticate('',`Bearer ${token}`,null,'read'),503,'configuration_missing');await expect(authenticate(raw,'Bearer bad',null,'read'),401,'unauthorized');await expect(authenticate(raw,`Bearer ${token}`,'alpha','write'),403,'scope_denied');await expect(authenticate(raw,`Bearer ${token}`,'beta','read'),403,'account_denied');assert.equal((await authenticate(raw,`Bearer ${'y'.repeat(32)}`,'beta','admin')).id,'admin');assert.throws(()=>mutationHeaders(new Headers()),(e:unknown)=>e instanceof OpError&&e.status===428);assert.throws(()=>mutationHeaders(new Headers({'x-confirm-write':'true'})),(e:unknown)=>e instanceof OpError&&e.status===400)});
test('vault decrypts Python vector and round trips',async()=>{const v=new Vault('11'.repeat(32),'alpha');assert.deepEqual(await v.open('z9AvTlJbpdDaGZ3UqSx1+PtI3QpWzd6SbbEX+Y/sh4UsdeY='),{a:1});assert.deepEqual(await v.open(await v.seal({a:1})),{a:1})});
test('journal replay conflict unknown rejected omitted and rate persistence',async()=>{const mem=new Mem(),clock=()=>120;const store=new AccountStore(mem,new Vault('22'.repeat(32),'alpha'),clock);const key='k'.repeat(16);await store.manage('create',{},'p',key);const first=await store.execute('x',{},'p','z'.repeat(16),true,async()=>({ok:true}),()=>1);assert.deepEqual(await store.execute('x',{},'p','z'.repeat(16),true,async()=>({bad:true}),()=>1),first);await expect(store.execute('x',{a:1},'p','z'.repeat(16),true,async()=>null,()=>0),409,'idempotency_conflict');await expect(store.execute('bad',{},'p','q'.repeat(16),true,async()=>{throw new OpError(400,'invalid_arguments')},()=>0),400,'invalid_arguments');await expect(store.execute('unknown',{},'p','w'.repeat(16),true,async()=>{throw new Error()},()=>1),409,'outcome_unknown');await expect(store.execute('unknown',{},'p','w'.repeat(16),true,async()=>null,()=>0),409,'outcome_unknown');const huge='a'.repeat(17000);await store.execute('huge',{},'p','h'.repeat(16),true,async()=>({huge}),()=>1);await expect(store.execute('huge',{},'p','h'.repeat(16),true,async()=>null,()=>0),409,'succeeded_result_not_cached');for(let i=0;i<25;i++)await store.execute('read',{},'p',undefined,false,async()=>null,()=>0);await expect(store.execute('read',{},'p',undefined,false,async()=>null,()=>0),429,'rate_limited')});
test('redaction removes nested secret-named keys',()=>assert.deepEqual(redact({ok:1,token:'x',nested:{cookie:'x',safe:true},list:[{password:'x',v:1}]}),{ok:1,nested:{safe:true},list:[{v:1}]}));
