import assert from 'node:assert/strict';
import test from 'node:test';
import { QR_APPROVAL_OPS } from '../src/steam/qr-approval.ts';
import { SteamTransport } from '../src/steam/transport.ts';
import { Writer, decode, get } from '../src/steam/protobuf.ts';
import type { OpContext, Json } from '../src/types.ts';

type Obj = Record<string, Json>;
const CLIENT = '72623859790382856', STEAM = '1230066625199609624', VERSION = 513;
const URL_QR = `https://s.team/q/${VERSION}/${CLIENT}`;
// Synthetic key bytes range(20), NOT an account secret. Reference generated by
// Python stdlib hmac.new(bytes(range(20)), struct.pack('<HQQ', 513,
// 0x0102030405060708, 0x1112131415161718), hashlib.sha256).hexdigest().
const SYNTHETIC_KEY = 'AAECAwQFBgcICQoLDA0ODxAREhM=';
const SIGNATURE = '00fb1492a380e1814185ccaeace85aeaa83b2c9a9f770922a28797b43e475552';
function token(sub = STEAM, exp = 4102444800, aud = ['mobile']): string {
  return `synthetic.${Buffer.from(JSON.stringify({ sub, exp, aud })).toString('base64url')}.synthetic`;
}
const info = (v = VERSION) => new Writer().string(1, '192.0.2.1').string(2, 'synthetic-region').string(3, 'synthetic-city')
  .string(4, 'synthetic-state').string(5, 'ZZ').uint(6, 2).string(7, 'Synthetic Browser').uint(8, v)
  .uint(9, 2).bool(10, true).bool(11, true).uint(12, 1).uint(13, 0).uint(14, 0).finish();
type Seen = { url: string; method: string | undefined; params: URLSearchParams };
function context(responses = [info(), new Uint8Array()], seen: Seen[] = []): OpContext {
  return { scope: 'admin', state: {
    session: { platform: 'mobile', steam_id: STEAM, access_token: token(), access_expires_at: 4102444800 },
    guard: { shared_secret: SYNTHETIC_KEY },
  }, transport: new SteamTransport(async (url, init) => {
    seen.push({ url, method: init.method, params: new URLSearchParams(String(init.body)) });
    const body = responses.shift(); assert.ok(body, 'unexpected synthetic request');
    return new Response(body, { headers: { 'x-eresult': '1' } });
  }) };
}
const op = (n: string) => QR_APPROVAL_OPS.find(x => x.name === `session.qr_${n}`)!;
const run = (c: OpContext, n: string, a: Obj) => op(n).run(c, a);
async function review(c: OpContext): Promise<Obj> { return await run(c, 'inspect', { qr_url: URL_QR }) as Obj; }
const message = (s: Seen) => decode(Buffer.from(s.params.get('input_protobuf_encoded')!, 'base64'));

test('admin-only specs distinguish inspection from explicitly confirmed mutation', () => {
  assert.deepEqual(QR_APPROVAL_OPS.map(x => [x.name, x.scope, x.mutating]), [
    ['session.qr_inspect', 'admin', false], ['session.qr_approve', 'admin', true], ['session.qr_deny', 'admin', true],
  ]);
  for (const s of QR_APPROVAL_OPS) assert.equal(s.schema.additionalProperties, false);
});
test('official inspect and approve protobuf plus Python HMAC synthetic reference', async () => {
  const seen: Seen[] = [], c = context(undefined, seen), r = await review(c);
  assert.equal(seen.length, 1); assert.equal(seen[0]!.method, 'POST');
  assert.equal(seen[0]!.url, 'https://api.steampowered.com/IAuthenticationService/GetAuthSessionInfo/v1');
  assert.equal(seen[0]!.params.get('access_token'), token());
  const i = message(seen[0]!); assert.deepEqual([...i.keys()], [1]); assert.equal(i.get(1)![0]!.wire, 0); assert.equal(get.int(i, 1), BigInt(CLIENT));
  assert.equal(r.status, 'review_required'); assert.equal(r.requires_confirmation, true);
  assert.equal(r.device_friendly_name, 'Synthetic Browser'); assert.equal(r.city, 'synthetic-city');
  assert.equal(r.requestor_location_mismatch, true); assert.equal(r.high_usage_login, true);
  assert.match(String(r.review_handle), /^[0-9a-f]{48}$/); assert.ok(Number(r.expires_at) <= Date.now() / 1000 + 120);
  const stored = c.state.qr_review as Obj; assert.equal(stored.client_id, CLIENT); assert.equal(stored.version, VERSION); assert.equal(stored.steam_id, STEAM);
  assert.ok(!JSON.stringify(r).includes(SYNTHETIC_KEY)); assert.ok(!JSON.stringify(r).includes(token()));
  assert.deepEqual(await run(c, 'approve', { review_handle: r.review_handle! }), { status: 'approved' });
  assert.equal(seen.length, 2); assert.equal(c.state.qr_review, undefined);
  assert.equal(seen[1]!.url, 'https://api.steampowered.com/IAuthenticationService/UpdateAuthSessionWithMobileConfirmation/v1');
  assert.equal(seen[1]!.params.get('access_token'), token());
  const m = message(seen[1]!); assert.deepEqual([...m.keys()], [1, 2, 3, 4, 5, 6]);
  assert.deepEqual([...m.values()].map(x => x[0]!.wire), [0, 0, 1, 2, 0, 0]);
  assert.equal(get.int(m, 1), BigInt(VERSION)); assert.equal(get.int(m, 2), BigInt(CLIENT)); assert.equal(get.int(m, 3), BigInt(STEAM));
  assert.equal(Buffer.from(get.bytes(m, 4)!).toString('hex'), SIGNATURE);
  assert.equal(get.int(m, 5), 1n); assert.equal(get.int(m, 6), 1n);
  await assert.rejects(run(c, 'approve', { review_handle: r.review_handle! }), /qr_review_handle_mismatch/);
  assert.equal(seen.length, 2);
});
test('denial uses the same inspected binding and signature, confirm false', async () => {
  const seen: Seen[] = [], c = context(undefined, seen), r = await review(c);
  assert.deepEqual(await run(c, 'deny', { review_handle: r.review_handle! }), { status: 'denied' });
  const m = message(seen[1]!); assert.equal(get.int(m, 5), 0n);
  assert.equal(Buffer.from(get.bytes(m, 4)!).toString('hex'), SIGNATURE); assert.equal(c.state.qr_review, undefined);
});
test('scope/session/secret/token gates reject before any network', async () => {
  const cases: ((c: OpContext) => void)[] = [
    c => { c.scope = 'read'; }, c => { c.scope = 'write'; }, c => { delete c.state.session; },
    c => { (c.state.session as Obj).platform = 'web'; }, c => { delete (c.state.session as Obj).access_token; },
    c => { (c.state.session as Obj).steam_id = '01'; }, c => { (c.state.session as Obj).steam_id = '18446744073709551616'; },
    c => { (c.state.session as Obj).access_expires_at = 0; }, c => { delete (c.state.session as Obj).access_expires_at; },
    c => { (c.state.session as Obj).access_token = token(STEAM, 1); }, c => { (c.state.session as Obj).access_token = token('1'); },
    c => { (c.state.session as Obj).access_token = token(STEAM, 4102444800, ['web']); },
    c => { (c.state.session as Obj).access_token = token(STEAM, 4102444800, ['mobile', 'derive']); },
    c => { delete c.state.guard; }, c => { (c.state.guard as Obj).shared_secret = 'bad'; },
    c => { (c.state.guard as Obj).shared_secret = 'AB=='; }, c => { (c.state.guard as Obj).shared_secret = ''; },
  ];
  for (const change of cases) {
    const c = context(); change(c);
    for (const n of ['inspect', 'approve', 'deny']) await assert.rejects(run(c, n, n === 'inspect' ? { qr_url: URL_QR } : { review_handle: 'a'.repeat(48) }));
    assert.equal(c.transport.requestCount, 0);
  }
});
test('strict canonical URL bounds and caller metadata/signatures never reach upstream', async () => {
  for (const url of [URL_QR + '/', URL_QR + '?x=1', URL_QR + '#x', URL_QR.replace('https:', 'http:'),
    URL_QR.replace('s.team', 'S.TEAM'), URL_QR.replace('s.team', 's.team:443'), URL_QR.replace('s.team', 's.team.evil.invalid'),
    URL_QR.replace('/513/', '/0513/'), 'https://s.team/q/65536/1', 'https://s.team/q/1/18446744073709551616',
    'https://s.team/q/1/01', 'https://s.team/q/1/+1', 'https://s.team/q/1/%31', ' ' + URL_QR, URL_QR + '\n']) {
    const c = context(); await assert.rejects(run(c, 'inspect', { qr_url: url }), /invalid_arguments/); assert.equal(c.transport.requestCount, 0);
  }
  const c = context();
  await assert.rejects(run(c, 'inspect', { qr_url: URL_QR, metadata: {} }), /invalid_arguments/);
  await assert.rejects(run(c, 'approve', { review_handle: 'a'.repeat(48), signature: 'caller' }), /invalid_arguments/);
  assert.equal(c.transport.requestCount, 0);
  for (const [v, client] of [[0, '0'], [65535, '18446744073709551615']] as const) {
    const d = context([info(v)]); await run(d, 'inspect', { qr_url: `https://s.team/q/${v}/${client}` });
    assert.equal((d.state.qr_review as Obj).client_id, client);
  }
});
test('wrong handle, expiry, changed account/token/secret are rejected before submission', async () => {
  for (const n of ['approve', 'deny']) {
    const c = context(), r = await review(c);
    await assert.rejects(run(c, n, { review_handle: 'f'.repeat(48) }), /qr_review_handle_mismatch/); assert.equal(c.transport.requestCount, 1);
    (c.state.qr_review as Obj).expires_at = 0;
    await assert.rejects(run(c, n, { review_handle: r.review_handle! }), /qr_review_expired/); assert.equal(c.transport.requestCount, 1); assert.equal(c.state.qr_review, undefined);
    for (const change of [
      (d: OpContext) => { Object.assign(d.state.session as Obj, { steam_id: '1', access_token: token('1') }); },
      (d: OpContext) => { (d.state.session as Obj).access_token = token(STEAM, 4102444799); },
      (d: OpContext) => { (d.state.guard as Obj).shared_secret = 'AAAAAAAAAAAAAAAAAAAAAAAAAAA='; },
    ]) {
      const d = context(), q = await review(d); change(d);
      await assert.rejects(run(d, n, { review_handle: q.review_handle! }), /qr_review_session_changed/);
      assert.equal(d.transport.requestCount, 1); assert.equal(d.state.qr_review, undefined);
    }
  }
});
test('uncertain submission consumes handle and cannot be retried', async () => {
  const c = context(), r = await review(c); let calls = 0;
  c.transport = new SteamTransport(async () => { calls++; assert.equal(c.state.qr_review, undefined); throw new Error('synthetic uncertainty'); });
  await assert.rejects(run(c, 'approve', { review_handle: r.review_handle! }));
  assert.equal(c.state.qr_review, undefined);
  await assert.rejects(run(c, 'approve', { review_handle: r.review_handle! }), /qr_review_handle_mismatch/); assert.equal(calls, 1);
});
test('malformed/mismatched inspection replaces old review without approving', async () => {
  for (const body of [info(VERSION + 1), new Uint8Array(), new Writer().string(8, '513').finish(), new Writer().uint(8, VERSION).uint(10, 2).finish()]) {
    const c = context([info(), body]), r = await review(c);
    await assert.rejects(review(c), /upstream_invalid_response/); assert.equal(c.state.qr_review, undefined);
    await assert.rejects(run(c, 'approve', { review_handle: r.review_handle! }), /qr_review_handle_mismatch/); assert.equal(c.transport.requestCount, 2);
  }
});
