import { OpError, type AccountState, type Json } from './types.ts';
import { redact } from './http.ts'; import { Vault } from './vault.ts';
type Intent={digest:string;status:string;operation:string;created_at:number;result?:Json;result_omitted?:boolean;error_status?:number;error_code?:string}; type RecordV={exists:boolean;state:AccountState;journal:Record<string,Intent>;version:number;rate:{minute?:number;count?:number}};
type Storage={get<T=unknown>(key:string):Promise<T|undefined>;put(value:Record<string,unknown>):Promise<void>}; const te=new TextEncoder();
function canonical(v:Json):string{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical((v as Record<string,Json>)[k]!)).join(',')+'}';} async function hash(s:string){const a=new Uint8Array(await crypto.subtle.digest('SHA-256',te.encode(s)));return [...a].map(x=>x.toString(16).padStart(2,'0')).join('');}
export class AccountStore {private chain=Promise.resolve(); constructor(private storage:Storage,private vault:Vault,private clock=()=>Date.now()/1000){} private async load():Promise<RecordV>{const e=await this.storage.get<string>('account-v1');return e?await this.vault.open(e) as RecordV:{exists:false,state:{},journal:{},version:0,rate:{}};} private async save(r:RecordV){const updates:Record<string,unknown>={};for(const [slot,i] of Object.entries(r.journal)){const x={...i};if(x.result&&te.encode(JSON.stringify(x.result)).length>16384){delete x.result;x.result_omitted=true;}updates['intent:'+slot]=await this.vault.seal(x as unknown as Json);}const compact={...r,journal:{}};updates['account-v1']=await this.vault.seal(compact as unknown as Json);if(String(updates['account-v1']).length>120000)throw new OpError(413,'account_state_too_large');await this.storage.put(updates);} private async locked<T>(fn:()=>Promise<T>){const previous=this.chain;let release!:()=>void;this.chain=new Promise<void>(r=>release=r);await previous;try{return await fn();}finally{release();}}
 private limit(r:RecordV){const minute=Math.floor(this.clock()/60), count=r.rate.minute===minute?(r.rate.count??0):0;if(count>=30)throw new OpError(429,'rate_limited');r.rate={minute,count:count+1};} private meta(r:RecordV):Json{return {exists:r.exists,version:r.version};}
 private async prepare(r:RecordV,principal:string,key:string,op:string,args:Record<string,Json>):Promise<[string,Intent,boolean]>{const slot=await hash(principal+'\0'+key), digest=await hash(canonical([op,args]));let old=r.journal[slot];const saved=await this.storage.get<string>('intent:'+slot);if(saved)old=await this.vault.open(saved) as Intent;if(old){if(old.digest!==digest)throw new OpError(409,'idempotency_conflict');if(old.status==='rejected')throw new OpError(old.error_status??400,old.error_code??'rejected');if(old.status!=='succeeded')throw new OpError(409,'outcome_unknown');if(old.result_omitted)throw new OpError(409,'succeeded_result_not_cached');return [slot,old,true];}const i:Intent={digest,status:'prepared',operation:op,created_at:Math.floor(this.clock())};r.journal[slot]=i;return [slot,i,false];}
 async info(){return this.locked(async()=>{const r=await this.load();if(!r.exists)throw new OpError(404,'account_not_found');return this.meta(r);});}
 async manage(action:string,args:Record<string,Json>,principal:string,key:string){return this.locked(async()=>{const r=await this.load();if(action==='export'){if(!r.exists)throw new OpError(404,'account_not_found');this.limit(r);await this.save(r);return {format:'steam-worker-state-v1',envelope:await this.vault.seal({state:r.state})};}if(action==='import'){if(Object.keys(args).length===1&&typeof args.envelope==='string'){try{args=await this.vault.open(args.envelope) as Record<string,Json>;}catch{throw new OpError(400,'invalid_envelope');}}if(Object.keys(args).length!==1||!args.state||typeof args.state!=='object'||Array.isArray(args.state))throw new OpError(400,'invalid_state');}else if(Object.keys(args).length)throw new OpError(400,'unexpected_arguments');const [,intent,replay]=await this.prepare(r,principal,key,'account.'+action,args);if(replay)return this.meta(r);if(action==='create'){if(r.exists)throw new OpError(409,'account_exists');r.exists=true;r.state={};}else if(action==='delete'||action==='import'){if(!r.exists)throw new OpError(404,'account_not_found');r.state=action==='import'?args.state as AccountState:{};r.exists=action!=='delete';}else throw new OpError(404,'not_found');this.limit(r);r.version++;intent.status='succeeded';intent.result=this.meta(r);await this.save(r);return intent.result;});}
 async execute(operation:string,args:Record<string,Json>,principal:string,key:string|undefined,mutating:boolean,run:(state:AccountState)=>Promise<Json>,requests:()=>number){return this.locked(async()=>{const r=await this.load();if(!r.exists)throw new OpError(404,'account_not_found');let intent:Intent|undefined;if(mutating){if(!key)throw new OpError(400,'idempotency_key_required');const [,i,replay]=await this.prepare(r,principal,key,operation,args);intent=i;if(replay)return i.result!;}this.limit(r);await this.save(r);if(intent){intent.status='in_flight';await this.save(r);}try{const result=redact(await run(r.state));r.version++;if(intent){intent.status='succeeded';intent.result=result;}await this.save(r);return result;}catch(e){if(intent){if(e instanceof OpError&&requests()===0){intent.status='rejected';intent.error_status=e.status;intent.error_code=e.code;await this.save(r);throw e;}intent.status='unknown';await this.save(r);throw new OpError(409,'outcome_unknown');}await this.save(r);if(e instanceof OpError)throw e;throw new OpError(502,'upstream_failed');}});}
}
