import { OpError, type Json, type Scope } from './types.ts';

export const MAX_BODY = 131072;
export const SLUG = /^[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}$/;
const IDEM = /^[A-Za-z0-9_-]{16,128}$/;
const SECRET = ['password','secret','token','cookie','authorization','signature','revocation','recovery','auth_code','apikey','api_key','request_id','client_id','mafile','wallet_code'];
export const SAFE_HEADERS = {'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; frame-ancestors 'none'",'Referrer-Policy':'no-referrer'};
type Principal={id:string;sha256:string;scopes:Scope[];accounts:string[]};
let memoRaw: string|undefined; let memoKeys: Principal[]|undefined;
function keys(raw: unknown): Principal[] { const text=typeof raw==='string'?raw:''; if(text===memoRaw&&memoKeys)return memoKeys; try { const v:unknown=JSON.parse(text); if(!Array.isArray(v)||!v.length) throw 0; const out=v.map(x=>{if(!x||typeof x!=='object')throw 0; const k=x as Record<string,unknown>; if(typeof k.id!=='string'||!SLUG.test(k.id)||typeof k.sha256!=='string'||!/^[0-9a-f]{64}$/.test(k.sha256)||!Array.isArray(k.scopes)||!k.scopes.every(s=>s==='read'||s==='write'||s==='admin')||!Array.isArray(k.accounts)||!k.accounts.every(a=>typeof a==='string'&&(a==='*'||SLUG.test(a))))throw 0; return {id:k.id,sha256:k.sha256,scopes:k.scopes as Scope[],accounts:k.accounts as string[]};}); if(new Set(out.map(x=>x.id)).size!==out.length)throw 0; memoRaw=text;memoKeys=out;return out;}catch{throw new OpError(503,'configuration_missing');}}
function hex(bytes: Uint8Array){return [...bytes].map(x=>x.toString(16).padStart(2,'0')).join('');}
function same(a:string,b:string){if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0;}
export async function authenticate(raw:unknown, authorization:string|null, account:string|null, scope:Scope):Promise<Principal>{const configured=keys(raw);if(!authorization?.startsWith('Bearer ')||authorization.length-7<32||authorization.length-7>512)throw new OpError(401,'unauthorized');const digest=hex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(authorization.slice(7)))));for(const p of configured)if(same(p.sha256,digest)){if(!p.scopes.includes(scope)&&!p.scopes.includes('admin'))throw new OpError(403,'scope_denied');if(account&&!p.accounts.includes(account)&&!(p.scopes.includes('admin')&&p.accounts.includes('*')))throw new OpError(403,'account_denied');return p;}throw new OpError(401,'unauthorized');}
export function effective(p:Principal):Scope{return p.scopes.includes('admin')?'admin':p.scopes.includes('write')?'write':'read';}
export function mutationHeaders(h:Headers):string {if(h.get('x-confirm-write')!=='true')throw new OpError(428,'write_confirmation_required');const k=h.get('idempotency-key')??'';if(!IDEM.test(k))throw new OpError(400,'idempotency_key_required');return k;}
export async function body(request:Request):Promise<Record<string,Json>> {const n=request.headers.get('content-length');if(n){const v=Number(n);if(!Number.isInteger(v)||v<0)throw new OpError(400,'invalid_length');if(v>MAX_BODY)throw new OpError(413,'body_too_large');}const reader=request.body?.getReader();const chunks:Uint8Array[]=[];let total=0;if(reader)try{for(;;){const x=await reader.read();if(x.done)break;total+=x.value.byteLength;if(total>MAX_BODY){await reader.cancel();throw new OpError(413,'body_too_large');}chunks.push(x.value);}}finally{reader.releaseLock();}let raw='';if(total) {const all=new Uint8Array(total);let at=0;for(const c of chunks){all.set(c,at);at+=c.length;}raw=new TextDecoder('utf-8', { fatal: true, ignoreBOM: true }).decode(all);}try {const v:unknown=JSON.parse(raw||'{}');if(!v||Array.isArray(v)||typeof v!=='object')throw 0;return v as Record<string,Json>;}catch{throw new OpError(400,'invalid_json');}}
export function redact(v:Json):Json {if(Array.isArray(v))return v.map(redact);if(v&&typeof v==='object'){const o:Record<string,Json>={};for(const [k,x] of Object.entries(v))if(!SECRET.some(s=>k.toLowerCase().includes(s)))o[k]=redact(x);return o;}return v;}
export function reply(value:Json,status=200):Response{return new Response(JSON.stringify(value),{status,headers:{...SAFE_HEADERS,'Content-Type':'application/json; charset=utf-8'}});}
export function bounded<T>(p:Promise<T>,ms:number,code:string):Promise<T>{return Promise.race([p,new Promise<T>((_,reject)=>setTimeout(()=>reject(new OpError(503,code)),ms))]);}
