import { DurableObject } from 'cloudflare:workers';
import { OpError, type Json, type Scope } from './types.ts'; import { authenticate, body, bounded, effective, mutationHeaders, reply, SLUG } from './http.ts'; import { AccountStore } from './account.ts'; import { Vault } from './vault.ts'; import { DirectoryStore } from './directory.ts'; import { HTML, consoleHeaders } from './console.ts';
import { OPERATIONS, OPERATIONS_JSON, createTransport, describeOperations, validateArgs } from './steam/registry.ts';
type Env={API_KEYS_JSON?:string;STATE_KEY_HEX?:string;ACCOUNTS:DurableObjectNamespace;DIRECTORY:DurableObjectNamespace};
const descriptions=describeOperations(); const operationsJson=OPERATIONS_JSON; const policies=new Map(descriptions.map(x=>[x.name,{scope:x.scope,mutating:x.mutating}]));
function route(method:string,path:string):[string,string?,string?]{if(method==='GET'&&path==='/')return ['index'];if(method==='GET'&&path==='/health')return ['health'];if(method==='GET'&&path==='/v1/operations')return ['operations'];if(method==='GET'&&path==='/v1/accounts')return ['list'];const m=/^\/v1\/accounts\/([a-zA-Z0-9][a-zA-Z0-9_-]{0,63})(?:\/(import|export|operations\/([a-zA-Z0-9_.-]{1,150})))?$/.exec(path);if(!m)throw new OpError(404,'not_found');const [,account,action,op]=m;if(op&&method==='POST')return ['operation',account,op];if(!action&&['GET','PUT','DELETE'].includes(method))return [{GET:'info',PUT:'create',DELETE:'delete'}[method]!,account];if((action==='import'||action==='export')&&method==='POST')return [action,account];throw new OpError(405,'method_not_allowed');}
function policy(action:string,op?:string):{scope:Scope;mutating:boolean}{if(action==='operation'){const p=policies.get(op??'');if(!p)throw new OpError(404,'operation_not_found');if(p.mutating&&p.scope==='read')throw new OpError(503,'invalid_operation_policy');return p;}return {scope:(action==='info'||action==='operations')?'read':'admin',mutating:['create','delete','import','export'].includes(action)};}
async function authorize(r:Request,env:Env){const [action,account,op]=route(r.method,new URL(r.url).pathname);const p=policy(action,op),principal=await authenticate(env.API_KEYS_JSON,r.headers.get('authorization'),account??null,p.scope);return {action,account,op,principal,key:p.mutating?mutationHeaders(r.headers):undefined,mutating:p.mutating};}
function error(e:unknown){return reply({error:{code:e instanceof OpError?e.code:'internal_error'}},e instanceof OpError?e.status:500);}
export default {async fetch(request:Request,env:Env):Promise<Response>{try{const path=new URL(request.url).pathname;if(request.method==='GET'&&path==='/')return new Response(HTML,{headers:consoleHeaders()});if(request.method==='GET'&&path==='/health')return reply({ok:true});const a=await authorize(request,env);if(a.action==='operations')return new Response(operationsJson,{headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});if(a.action==='list'){const d=env.DIRECTORY.get(env.DIRECTORY.idFromName('directory-v1'));const res=await bounded(d.fetch(new Request('https://example.com/accounts')),10000,'directory_unavailable');if(!res.ok)throw new OpError(503,'directory_unavailable');const data=await res.json() as {accounts?:unknown};const accounts=Array.isArray(data.accounts)?data.accounts.filter(x=>typeof x==='string'&&(a.principal.accounts.includes(x)||(a.principal.scopes.includes('admin')&&a.principal.accounts.includes('*')))):[];return reply({accounts});}const stub=env.ACCOUNTS.get(env.ACCOUNTS.idFromName('account-v1:'+a.account));const response=await bounded(stub.fetch(request),60000,'account_unavailable');if((a.action==='create'||a.action==='delete')&&response.ok){try{const x=await response.clone().json() as {exists?:unknown};const d=env.DIRECTORY.get(env.DIRECTORY.idFromName('directory-v1'));await bounded(d.fetch(new Request('https://example.com/record',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({account:a.account,exists:!!x.exists})})),10000,'directory_unavailable');}catch(e){if(e instanceof OpError)throw e;}}return response;}catch(e){return error(e);}}};
export class SteamAccount extends DurableObject<Env>{private store?:AccountStore;private init?:Promise<AccountStore>;private async getStore(account:string){if(this.store)return this.store;this.init??=(async()=>{try{return new AccountStore(this.ctx.storage as never,new Vault(this.env.STATE_KEY_HEX??'',account));}catch{throw new OpError(503,'configuration_missing');}})();return this.store=await this.init;}override async fetch(request:Request){try{const a=await authorize(request,this.env);if(!a.account)throw new OpError(404,'not_found');const store=await this.getStore(a.account);if(a.action==='info')return reply(await store.info());const args=await body(request);if(a.action==='operation'){if(Object.keys(args).some(k=>k!=='arguments')||('arguments'in args&&(!args.arguments||typeof args.arguments!=='object'||Array.isArray(args.arguments))))throw new OpError(400,'invalid_arguments');const spec=OPERATIONS.get(a.op??'');if(!spec)throw new OpError(404,'operation_not_found');const values=validateArgs(spec,(args.arguments??{}) as Record<string,Json>);const t=createTransport();try{const result=await store.execute(spec.name,values,a.principal.id,a.key,a.mutating,async state=>spec.run({state,transport:t,scope:effective(a.principal)},values),()=>t.requestCount);return reply({result});}finally{(t as {close?:()=>void}).close?.();}}return reply(await store.manage(a.action,args,a.principal.id,a.key!));}catch(e){return error(e);}}}
export class AccountDirectory extends DurableObject<Env>{private store=new DirectoryStore(this.ctx.storage as never);override async fetch(request:Request){try{const path=new URL(request.url).pathname;if(request.method==='GET'&&path==='/accounts')return reply({accounts:await this.store.accounts()});if(request.method==='POST'&&path==='/record'){const x=await body(request);if(typeof x.account!=='string'||!SLUG.test(x.account)||typeof x.exists!=='boolean')throw new OpError(400,'invalid_arguments');await this.store.record(x.account,x.exists);return reply({ok:true});}throw new OpError(404,'not_found');}catch(e){return error(e);}}}
